import api from './api.js'

export const dispatchApi = {
  workers:()=>api.get('/dispatch/setup/workers'),
  saveWorker:body=>api.post('/dispatch/setup/workers',body),
  workerHistory:()=>api.get('/dispatch/setup/delegations'),
  delegateWorker:body=>api.post('/dispatch/delegation',body),
  endWorkerDelegation:token=>api.post('/dispatch/delegation/end',{token}),

  currentPackingRun: () => api.get('/dispatch/packing-runs/current'),
  startPackingRun: checkerUserId => api.post('/dispatch/packing-runs', {checkerUserId}),
  endPackingRun: id => api.post(`/dispatch/packing-runs/${id}/end`),
  claimOrder: (id,stage,sessionId) => api.post(`/dispatch/orders/${id}/claim`, {stage,sessionId}),
  releaseOrder: id => api.post(`/dispatch/orders/${id}/release`),
  boxLabel: id => api.get(`/dispatch/boxes/${id}/label`),
  unpackBox: (id,body) => api.post(`/dispatch/boxes/${id}/unpack`,body),
  correctBarcode: body => api.put('/dispatch/item-barcode',body),
  reportLookups: () => api.get('/dispatch/report-lookups'),
  syncSchedules: company => api.get('/dispatch/sync-schedules',{params:{company}}),
  saveSyncSchedule: (company,body) => api.put(`/dispatch/sync-schedules/${company}`,body),
  pushPacked: company => api.post('/dispatch/packed-export',{company}),
  packedExport: company => api.get('/dispatch/packed-export',{params:{company}}),
  syncStatus: params => api.get('/dispatch/sync-status',{params}),
  reports: params => api.get('/dispatch/reports',{params}),
  staff: () => api.get('/dispatch/setup/staff'),
  assignStaffRole: (id,role) => api.put(`/dispatch/setup/staff/${id}/role`,{role}),
  refreshUoms: () => api.post('/dispatch/setup/refresh-uoms'),
  currentAssemblySession: () => api.get('/dispatch/assembly-sessions/current'),
  startAssemblySession: () => api.post('/dispatch/assembly-sessions'),
  endAssemblySession: id => api.post(`/dispatch/assembly-sessions/${id}/end`),
  assemblySessions: params => api.get('/dispatch/assembly-sessions', {params}),
  assemblySessionEvents: id => api.get(`/dispatch/assembly-sessions/${id}/events`),
  chillerMovements: params => api.get('/dispatch/chillers/movements', {params}),
  stocktakes: params => api.get('/dispatch/stocktakes', {params}),
  stocktakeCatalog: company => api.get('/dispatch/stocktakes/catalog', {params:{company}}),
  stocktake: id => api.get(`/dispatch/stocktakes/${id}`),
  startStocktake: body => api.post('/dispatch/stocktakes',body),
  saveStocktakeCount: (id,body) => api.put(`/dispatch/stocktakes/${id}/count`,body),
  completeStocktake: id => api.post(`/dispatch/stocktakes/${id}/complete`),
  exportStocktake: id => api.get(`/dispatch/stocktakes/${id}/export`,{responseType:'blob'}),
  syncDispatchItemRules: () => api.post('/dispatch/chillers/sync-item-rules'),
  chillerConfig: () => api.get('/dispatch/chillers/config'),
  saveChillerConfig: (body) => api.put('/dispatch/chillers/config', body),
  saveChillerMapping: (body) => api.post('/dispatch/chillers/mappings', body),
  deleteChillerMapping: (itemNo) => api.delete(`/dispatch/chillers/mappings/${encodeURIComponent(itemNo)}`),
  chillerWorklist: (userId, status = 'pending', filters = {}) => api.get('/dispatch/chillers/worklist', { params: { ...filters, userId: userId || undefined, status } }),
  chillerMonitor: () => api.get('/dispatch/chillers/monitor'),
  chillerStock: params => api.get('/dispatch/chillers/stock',{params}),
  // Registry
  importFromBc:  (companies) => api.post('/dispatch/import', { companies }),
  registryCompanies: ()      => api.get('/dispatch/registry-companies'),
  confirmation:  (companies, filters={}) => api.get('/dispatch/confirmation', { params: { ...filters, companies: companies?.join(',') || undefined } }),
  confirmationReport: (companies, filters={}) => api.get('/dispatch/confirmations/report', { params: { ...filters, companies: companies?.join(',') || undefined } }),
  getOrder:      (id)        => api.get(`/dispatch/orders/${id}`),
  confirmPart:   (id, part)  => api.post(`/dispatch/orders/${id}/confirm`, { part }),
  getUserCompanies: (userId) => api.get(`/dispatch/users/${userId}/companies`),
  setUserCompanies: (userId, companies) => api.put(`/dispatch/users/${userId}/companies`, { companies }),
  // Assignment
  unassigned:    ()          => api.get('/dispatch/unassigned'),
  packers:       ()          => api.get('/dispatch/packers'),
  assign:        (id, body)  => api.post(`/dispatch/orders/${id}/assign`, body),
  // Assembly
  assembly:       (userId)        => api.get('/dispatch/assembly', { params: { userId: userId || undefined } }),
  assemblers:     ()             => api.get('/dispatch/assemblers'),
  returnReasons:  (company)       => api.get('/dispatch/return-reasons', { params: { company } }),
  assemblyOrder:  (id, userId)    => api.get(`/dispatch/assembly/${id}`, { params: { userId: userId || undefined } }),
  saveAssemblyLine: (lineId, body) => api.put(`/dispatch/assembly/lines/${lineId}`, body),
  completeAssemblyPart: (id, part) => api.post(`/dispatch/assembly/${id}/complete-part`, { part }),
  // Packing
  packing:        (status='pending') => api.get('/dispatch/packing', {params:{status}}),
  vesselTypes:    ()        => api.get('/dispatch/vessel-types'),
  checkers:       ()        => api.get('/dispatch/checkers'),
  packingOrder:   (id)       => api.get(`/dispatch/packing/${id}`),
  startSession:   (id, body) => api.post(`/dispatch/packing/${id}/session`, body),
  openBox:        (id, body) => api.post(`/dispatch/packing/${id}/boxes`, body),
  addBoxLine:     (boxId, body) => api.post(`/dispatch/boxes/${boxId}/lines`, body),
  removeBoxLine:  (boxLineId) => api.delete(`/dispatch/box-lines/${boxLineId}`),
  closeBox:       (boxId, body) => api.post(`/dispatch/boxes/${boxId}/close`, body),
  boxByQr:        (qr)       => api.get(`/dispatch/box-by-qr/${encodeURIComponent(qr)}`),
  completePacking: (id)      => api.post(`/dispatch/packing/${id}/complete`),
  // Loading
  vehicles:       ()        => api.get('/dispatch/vehicles'),
  loadingSessions: ()       => api.get('/dispatch/loading'),
  createLoading:  (body)     => api.post('/dispatch/loading', body),
  loadingSession: (id)       => api.get(`/dispatch/loading/${id}`),
  scanBox:        (id, qrToken) => api.post(`/dispatch/loading/${id}/scan`, { qrToken }),
  removeLoadingLine: (loadingLineId) => api.delete(`/dispatch/loading-lines/${loadingLineId}`),
  closeLoading:   (id)       => api.post(`/dispatch/loading/${id}/close`),
  // Setup + BC master data
  setupVessels:   ()        => api.get('/dispatch/setup/vessels'),
  saveVessel:     (body)     => api.post('/dispatch/setup/vessels', body),
  deleteVessel:   (id)       => api.delete(`/dispatch/setup/vessels/${id}`),
  setupVehicles:  ()        => api.get('/dispatch/setup/vehicles', { params: { all: 1 } }),
  saveVehicle:    (body)     => api.post('/dispatch/setup/vehicles', body),
  deleteVehicle:  (id)       => api.delete(`/dispatch/setup/vehicles/${id}`),
  bcRoutes:       (companies) => api.get('/dispatch/bc-routes', { params: { companies: companies?.join(',') || undefined } }),
  bcSalespersons: (companies) => api.get('/dispatch/bc-salespersons', { params: { companies: companies?.join(',') || undefined } }),
}
